server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engly
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:82232}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        options:
          model: gpt-4o-mini

  threads:
    virtual:
      enabled: true

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}
    username: ${TELEGRAM_USERNAME}

google:
  docs:
    document-id: ${DOCUMENT_ID}
    credentials-path: ${DOCS_PATH}

trello:
  api:
    key: ${TRELLO_API_KEY}
    token: ${TOKEN_API_KEY}
    board-id: ${BOARD_ID}
    list-id: ${LIST_ID}